tagObject = {
	type: {
		ABE: "Agricultural and Biological Engineering",
		ABT: "Arabic Culture in Translation or Translation Skills",
		ABW: "Arabic Literature (Writings)",
		ACG: "Accounting: General",
		ACO: "Accounting: Occupational/Technical Variable Paced",
		ACR: "Heating/Ventilation/AC/Refrigeration: Tech/Trades ADE Adult Education",
		ADV: "Advertising",
		AEB: "Agricultural Economics and Business",
		AEC: "Agricultural Education and Communication AEE Agriculture and Extension Education",
		AER: "Automotive Mechanics",
		AFA: "African-American Studies",
		AFH: "African History",
		AFR: "Aerospace Studies",
		AFS: "African Studies",
		AGE: "Agricultural Engineering",
		AGG: "Agriculture - General",
		AGR: "Agronomy",
		AHM: "Amharic Language",
		AHT: "Amharic Culture in Translation or Translation Skills",
		AHW: "Amharic Literature (Writings)",
		AKA: "Akan Language",
		AKT: "Akan Culture in Translation or Translation Skills AKW Akan Literature (Writings)",
		ALS: "Agriculture and Life Sciences",
		AMH: "American History",
		AML: "American Literature",
		AMS: "American Studies",
		AMT: "Aviation Maintenance Technology",
		ANG: "Anthropology--Graduate",
		ANS: "Animal Science",
		ANT: "Anthropology",
		AOM: "Agricultural Operations Management",
		APA: "Applied Accounting",
		APK: "Applied Kinesiology",
		ARA: "Arabic Language",
		ARC: "Architecture",
		ARD: "Architectural Design",
		ARE: "Art Education",
		ARH: "Art History",
		ARR: "Autobody Repair and Refinishing",
		ART: "Art",
		ARV: "Art, Vocational",
		ASC: "Aviation Science: General",
		ASG: "Animal Science: General",
		ASH: "Asian History",
		ASL: "American Sign Language",
		ASN: "Asian Studies",
		AST: "Astronomy",
		ATE: "Animal Science Technology",
		ATF: "Aviation Technology: Flight",
		ATR: "Athletic Training",
		ATT: "Aviation Technology: Theory",
		AVM: "Aviation Management",
		AVS: "Avionics",
		AYM: "Aymara Language",
		BAN: "Commercial Banking (AIB Courses Only)",
		BCA: "Building Construction Apprenticeships",
		BCC: "Basic Clinical Clerkships (Required)",
		BCH: "Biochemistry (Biophysics)",
		BCN: "Building Construction",
		BCT: "Building Construction Trades",
		BCV: "Building Construction: Vocational",
		BME: "Biomedical Engineering",
		BMS: "Basic Medical Sciences",
		BOT: "Botany",
		BRC: "Banking Related Courses (Not AIB or IFE) ",
		BSC: "Biological Sciences",
		BTE: "Business Teacher Education",
		BUL: "Business Law",
		CAP: "Computer Applications",
		CAS: "Clinical Audiology and Speech Language Pathology",
		CAT: "Catalan Language",
		CBH: "Comparative Psychology and Animal Behavior",
		CCE: "Civil Construction Engineering",
		CCJ: "Criminology and Criminal Justice",
		CDA: "Computer Design/Architecture",
		CEG: "Civil Geotechnical Engineering ",
		CEN: "Computer Software Engineering ",
		CES: "Civil Engineering Structures",
		CET: "Computer Engineering Technology ",
		CGN: "Civil Engineering",
		CGS: "Computer General Studies",
		CHD: "Home Economics: Child Development",
		CHI: "Chinese",
		CHM: "Chemistry",
		CHR: "Chiropractic",
		CHS: "Chemistry - Specialized",
		CHT: "Chinese Culture in Translation or Translation Skills",
		CHW: "Chinese Literature (Writings)",
		CIS: "Computer Science and Information Systems ",
		CJB: "College Level Application in Criminal Justice ",
		CJC: "Corrections",
		CJD: "Criminal Justice Development",
		CJE: "Law Enforcement",
		CJJ: "Juvenile Justice",
		CJK: "Criminal Justice Basic Training (A.A.S or Vocational) ",
		CJL: "Law & Process",
		CJT: "Criminal Justice Technologies ",
		CLA: "Classical and Ancient Studies ",
		CLP: "Clinical Psychology",
		CLT: "Classical Culture in Translation or Translation Skills",
		CMC: "Corporate Media Communication",
		CMM: "Creek/Muskogee/Mikasuki",
		CNT: "Computer Networks",
		COA: "Home Economics: Consumer Affairs",
		COE: "Cooperative Education",
		COM: "Communication",
		COP: "Computer Programming",
		COS: "Cosmetology",
		COT: "Computing Theory",
		CPO: "Comparative Politics",
		CPS: "Comparative Policy Studies (Multinational) ",
		CPT: "Cardiopulmonary Technology",
		CRW: "Creative Writing",
		CSP: "Cosmetology - Specialized",
		CST: "Comparative Studies",
		CTE: "Home Economics: Clothing and Textiles ",
		CTS: "Computer Technology and Skills",
		CVT: "Cardiovascular Technology",
		CWR: "Civil Water Resources",
		CYP: "Community Psychology",
		CZE: "Czech Language",
		CZT: "Czech Culture in Translation or Translation Skills",
		CZW: "Czech Literature (Writings)",
		DAA: "Dance, Emphasis On Activity ",
		DAE: "Dance Education",
		DAN: "Dance",
		DAS: "Dairy Science",
		DCP: "Design, Construction and Planning ",
		DEA: "Dental Assisting",
		DEC: "Marketing and Distributive Education ",
		DEH: "Dental Hygiene",
		DEM: "Demography",
		DEN: "Dentistry",
		DEP: "Developmental Psychology",
		DES: "Dental Support",
		DIE: "Dietetics",
		DIG: "Digital Media",
		DIM: "Diesel, Hybrid, and Alternative Fuel Technology ",
		DSC: "Domestic Security",
		DTE: "Dental Laboratory Technology",
		DUT: "Dutch Language",
		EAB: "Experimental Analysis Of Behavior",
		EAP: "English As A Second Language for Academic Purposes ",
		EAS: "Aerospace Engineering",
		EBD: "Education: Emotional/Behavioral Disorders",
		ECH: "Engineering: Chemical",
	},
	level: ["Subcollegiate","Freshman","Sophomore","Junior","Senior","Graduate","Advanced Graduate","Doctoral"],
	college: {
		ECS:  "Egineering and Computer Science",
		BA : "Business Administration", 
		BHC : "Burnett Honors College", 
		CAH : "Arts & Humanities", 
		COM : "Medicine", 
		CON : "Nursing", 
		COS : "Sciences", 
		ECS : "Engineering and Computer Science", 
		ED : "Education", 
		HPA : "Health and Public Affairs", 
		OPT : "Optics", 
		RCHM : "Rosen College of Hospitality Management",
		UGST : "Undergraduate Studies/Interdisciplinary Studies"
	},
	department: {
			"ACCT": "Accounting",
			"BA": "Business",
			"ECON": "Economics",
			"FIN": "Finance",
			"MAN": "Management",
			"MIS": "Management Information Systems",
			"MAR": "Marketing",
			"HON": "Honors",
			"AS": "Africana Studies",
			"CAH": "Arts & Humanities",
			"ENG": "English",
			"FIEA": "Fla Interactive Entertainment Academy",
			"HIST": "History",
			"JUD": "Judaic Studies",
			"LAS": "Latin American Studies",
			"LANG": "Modern Languages",
			"MUSIC": "Music",
			"PHIL": "Philosophy",
			"SVAD": "School of Visual Arts & Design",
			"THEA": "Theatre",
			"WOM": "Women’s Studies",
			"WRITE": "Writing & Rhetoric",
			"MED": "Medicine",
			"BSBS": "Burnett School of Biomedical Sciences",
			"NURS": "Nursing",
			"ANTHRO": "Anthropology",
			"BIOL": "Biology",
			"CHEM": "Chemistry",
			"COMM": "Communication",
			"MATH": "Mathematics",
			"PHYS": "Physics",
			"POLS": "Political Science",
			"PSYCH": "Psychology",
			"COS": "Sciences",
			"SOC": "Sociology",
			"STAT": "Statistics",
			"AFROTC": "Air Force ROTC-Aerospace",
			"CECE": "Civil, Env & Const Eng",
			"CS": "Computer Science",
			"ECE": "Electrical & Computer Engineering",
			"ECS": "Engineering",
			"IEMS": "Industrial Eng & Management Systems",
			"MSE": "Materials Sci & Engineering",
			"MECH/AERO": "Mechanical & Aerospace Engineering",
			"AROTC": "Military Science-Army ROTC",
			"CFCS": "Child, Family & Comm Sciences",
			"ED": "Education",
			"E&HS": "Educational & Human Sciences",
			"TL&L": "Teaching, Learning & Leadership",
			"SC&DIS": "Communication Sciences & Disorders COM",
			"CJ": "Criminal Justice",
			"HPA": "Health & Public Affairs",
			"HMI": "Health Management & Informatics",
			"HP": "Health Professions",
			"LS": "Legal Studies",
			"PUB": "Public Administration",
			"AFF": "Public Affairs PUB",
			"SOWK": "Social Work",
			"OPT": "Optics",
			"FOOD&LODG": "Foodservice & Lodging Mgmt",
			"RCHM": "Hospitality Management",
			"SERV": "Hospitality Services HSP",
			"TEA": "Tourism, Events & Attractions",
			"INTERDISC": "Undergrad/Interdisc Studies"
	}

}




